"""empty message

Revision ID: 83b878b9bb16
Revises: e52656d201c7
Create Date: 2023-09-13 13:33:37.576385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b878b9bb16'
down_revision = 'e52656d201c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('players_club_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clubs', ['club_id'], ['id'])
        batch_op.drop_column('club')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('players_club_fkey', 'clubs', ['club'], ['id'])
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
